// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.1
// source: pkg/protos/monitors.proto

package monitors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CoinVoteMonitorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID          int32  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	Short       string `protobuf:"bytes,3,opt,name=Short,proto3" json:"Short,omitempty"`
	Votes       int64  `protobuf:"varint,4,opt,name=Votes,proto3" json:"Votes,omitempty"`
	LastUpdate  string `protobuf:"bytes,5,opt,name=LastUpdate,proto3" json:"LastUpdate,omitempty"`
}

func (x *CoinVoteMonitorResponse) Reset() {
	*x = CoinVoteMonitorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protos_monitors_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CoinVoteMonitorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoinVoteMonitorResponse) ProtoMessage() {}

func (x *CoinVoteMonitorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protos_monitors_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoinVoteMonitorResponse.ProtoReflect.Descriptor instead.
func (*CoinVoteMonitorResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protos_monitors_proto_rawDescGZIP(), []int{0}
}

func (x *CoinVoteMonitorResponse) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *CoinVoteMonitorResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CoinVoteMonitorResponse) GetShort() string {
	if x != nil {
		return x.Short
	}
	return ""
}

func (x *CoinVoteMonitorResponse) GetVotes() int64 {
	if x != nil {
		return x.Votes
	}
	return 0
}

func (x *CoinVoteMonitorResponse) GetLastUpdate() string {
	if x != nil {
		return x.LastUpdate
	}
	return ""
}

type CoinVoteMonitorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CoinID int32 `protobuf:"varint,1,opt,name=CoinID,proto3" json:"CoinID,omitempty"`
}

func (x *CoinVoteMonitorRequest) Reset() {
	*x = CoinVoteMonitorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protos_monitors_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CoinVoteMonitorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoinVoteMonitorRequest) ProtoMessage() {}

func (x *CoinVoteMonitorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protos_monitors_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoinVoteMonitorRequest.ProtoReflect.Descriptor instead.
func (*CoinVoteMonitorRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protos_monitors_proto_rawDescGZIP(), []int{1}
}

func (x *CoinVoteMonitorRequest) GetCoinID() int32 {
	if x != nil {
		return x.CoinID
	}
	return 0
}

var File_pkg_protos_monitors_proto protoreflect.FileDescriptor

var file_pkg_protos_monitors_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x6f, 0x6e,
	0x69, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x97, 0x01, 0x0a, 0x17,
	0x43, 0x6f, 0x69, 0x6e, 0x56, 0x6f, 0x74, 0x65, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x68, 0x6f,
	0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x56, 0x6f, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x56, 0x6f, 0x74, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x4c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x4c, 0x61, 0x73, 0x74, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0x30, 0x0a, 0x16, 0x43, 0x6f, 0x69, 0x6e, 0x56, 0x6f, 0x74,
	0x65, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x43, 0x6f, 0x69, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x43, 0x6f, 0x69, 0x6e, 0x49, 0x44, 0x32, 0x58, 0x0a, 0x0b, 0x56, 0x6f, 0x74, 0x65, 0x4d,
	0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x12, 0x49, 0x0a, 0x10, 0x43, 0x6f, 0x69, 0x6e, 0x4d, 0x6f,
	0x6e, 0x69, 0x74, 0x6f, 0x72, 0x56, 0x6f, 0x74, 0x65, 0x73, 0x12, 0x17, 0x2e, 0x43, 0x6f, 0x69,
	0x6e, 0x56, 0x6f, 0x74, 0x65, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x43, 0x6f, 0x69, 0x6e, 0x56, 0x6f, 0x74, 0x65, 0x4d, 0x6f,
	0x6e, 0x69, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30,
	0x01, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_protos_monitors_proto_rawDescOnce sync.Once
	file_pkg_protos_monitors_proto_rawDescData = file_pkg_protos_monitors_proto_rawDesc
)

func file_pkg_protos_monitors_proto_rawDescGZIP() []byte {
	file_pkg_protos_monitors_proto_rawDescOnce.Do(func() {
		file_pkg_protos_monitors_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_protos_monitors_proto_rawDescData)
	})
	return file_pkg_protos_monitors_proto_rawDescData
}

var file_pkg_protos_monitors_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_protos_monitors_proto_goTypes = []interface{}{
	(*CoinVoteMonitorResponse)(nil), // 0: CoinVoteMonitorResponse
	(*CoinVoteMonitorRequest)(nil),  // 1: CoinVoteMonitorRequest
}
var file_pkg_protos_monitors_proto_depIdxs = []int32{
	1, // 0: VoteMonitor.CoinMonitorVotes:input_type -> CoinVoteMonitorRequest
	0, // 1: VoteMonitor.CoinMonitorVotes:output_type -> CoinVoteMonitorResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_protos_monitors_proto_init() }
func file_pkg_protos_monitors_proto_init() {
	if File_pkg_protos_monitors_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_protos_monitors_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CoinVoteMonitorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protos_monitors_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CoinVoteMonitorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_protos_monitors_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_protos_monitors_proto_goTypes,
		DependencyIndexes: file_pkg_protos_monitors_proto_depIdxs,
		MessageInfos:      file_pkg_protos_monitors_proto_msgTypes,
	}.Build()
	File_pkg_protos_monitors_proto = out.File
	file_pkg_protos_monitors_proto_rawDesc = nil
	file_pkg_protos_monitors_proto_goTypes = nil
	file_pkg_protos_monitors_proto_depIdxs = nil
}
